// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: system.proto

package server

import (
	"context"

	"gonna/services/system-rpc/internal/logic"
	"gonna/services/system-rpc/internal/svc"
	"gonna/services/system-rpc/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) Ping(ctx context.Context, in *system.PingRequest) (*system.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
