// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: system.proto

package system_client

import (
	"context"

	"gonna/services/system-rpc/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingRequest  = system.PingRequest
	PingResponse = system.PingResponse

	System interface {
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
